spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keepnote6?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: GayatriMata1@.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082